### PR TITLE
Address bar type + use bugfix

### PR DESCRIPTION
**Pull request by sam-dixon**
Added event listeners for "focusout" and "focusin" events, so if the user clicks away from the document pane to click on the address bar, we will use the proper methods to get the editor state.

### CODE REVIEW

**Comment by MattWiethoff** [comment]
Looks like there's a browser method for this already: https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus

**Comment by sam-dixon** [comment]
> Looks like there's a browser method for this already: https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus

That's much easier :)

**Comment by sam-dixon** [comment]
Made some slight modifications:
- set the filename to "serenade-chrome-address-bar" if the document is unfocused so we can use this information with the client
- set the error state to true if we can't obtain the source and propagate this error to the client

**Review by tmacwill — APPROVED** [review]
lgtm!

**Pull request merged**
